import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import { dark, neobrutalism } from "@clerk/themes";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import { QueryClient } from "@tanstack/react-query";
import { ReactQueryClientProvider } from "@/provider/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: "../public/font/PlusJakartaSans-SemiBold.ttf",
  display: "swap",
});

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: { colorPrimary: "red" },
      }}
    >
      <ReactQueryClientProvider>
        <html lang="en" className={plusJakartaSans.className}>
          <body className="min-h-screen bg-[#F6F6F4]">
            <Toaster />
            {children}
          </body>
        </html>
      </ReactQueryClientProvider>
    </ClerkProvider>
  );
}
